spring.application.name=service-conformidad

# SQL Server
spring.datasource.url=jdbc:sqlserver://WEBIIS_DES01;databaseName=GestionRQ;encrypt=false;trustServerCertificate=true;integratedSecurity=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# IMPORTANTE: respetar exactamente los nombres de SQL Server
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
